name: Deploy only index.html and folders to Aruba via FTP

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Permette anche l'avvio manuale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.0
      with:
        server: ftp.filippomorano.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /www.filippomorano.com/projects/block-hunter/
        exclude: |
          **/*
          !index.html
          !game.js
          !css/**
          !js/**
          !data/**
          !assets/**
          !images/**
          !docs/**
          !.htaccess
